version: '3'
services:
  web:
    image: docker-node-express-mongoapp
    restart: unless-stopped
    build: ./
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    restart: unless-stopped

    ports:
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"
    restart: unless-stopped

    ports:
      - "1234:1234"